-- A
SELECT CICLO_FORM.NOMBRE
FROM CICLO_FORM
WHERE TIPO = 'GRADO SUPERIOR';

-- B
SELECT D.NOMBRE, D.AP1, D.AP2, D.DIRECCION
FROM DATOS_PERSONALES D, PROFESOR P
WHERE D.DNI = P.DNI; -- [D.TIPO = 'PROFESOR']

-- C
SELECT A.NOMBRE
FROM ASIGNATURA A
WHERE A.NUM_HORAS BETWEEN 150 AND 250; --[A.NUM_HORAS >= 150 AND A.NUM_HORAS <= 250]

-- D
SELECT D.NOMBRE, P.CUENTA
FROM DATOS_PERSONALES D, PROFESOR P
WHERE D.DNI = P.DNI;

-- E
SELECT M.DNI
FROM MATRICULA M
WHERE M.COD_ASIG = 3;

-- F
SELECT DNI
FROM IDIOMAS_PROF
WHERE COD_IDIOMA = 30;

-- G
SELECT NOMBRE
FROM ASIGNATURA
WHERE DNI_PROFESOR LIKE '89621477%'; -- [LIKE '89621477_']

-- H
SELECT DNI
FROM DATOS_PERSONALES
WHERE NOMBRE IN ('ANDREA', 'LUIS');