-- 1
CREATE TABLE EMPLEADOS(
    CLAVE_EMP VARCHAR(5),
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    CLAVE_DEPT NUMBER(1) NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY(CLAVE_EMP)
);

CREATE TABLE DEPARTAMENTO(
    CLAVE_DEPT NUMBER(1),
    NOMBRE VARCHAR(30) NOT NULL,
    PRESUPUESTO NUMBER(5) NOT NULL,
    CONSTRAINT PK_CLAVE_DEPT PRIMARY KEY(CLAVE_DEPT)
);

ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_DEPT FOREIGN KEY(CLAVE_DEPT) REFERENCES DEPARTAMENTO(CLAVE_DEPT);

-- 2
CREATE SEQUENCE seqClave_dept START WITH 1 INCREMENT BY 1 MAXVALUE 999 NOCYCLE;

INSERT INTO DEPARTAMENTO(CLAVE_DEPT, NOMBRE, PRESUPUESTO) VALUES(seqClave_dept.NEXTVAL, 'Personal', 80000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPT, NOMBRE, PRESUPUESTO) VALUES(seqClave_dept.NEXTVAL, 'Almacén', 70000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPT, NOMBRE, PRESUPUESTO) VALUES(seqClave_dept.NEXTVAL, 'Contabilidad', 60000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPT, NOMBRE, PRESUPUESTO) VALUES(seqClave_dept.NEXTVAL, 'Manufactura', 50000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPT, NOMBRE, PRESUPUESTO) VALUES(seqClave_dept.NEXTVAL, 'Empaque', 30000);

INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP01', 'Armando', 'López', 2);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP02', 'Tatiana', 'Vargas', 1);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP03', 'Laura','García', 3);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP04', 'Juan', 'Pérez', 4);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP05', 'Iván', 'López', 4);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP06', 'Margarita', 'Hernández', 1);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP07', 'Jesús', 'Pérez', 3);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP08', 'Toño', 'Flores', 2);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP09', 'Juan', 'López', 4);
INSERT INTO EMPLEADOS(CLAVE_EMP, NOMBRE, APELLIDO, CLAVE_DEPT) VALUES('EMP10', 'José', 'Hernández', 5);

-- 3
-- A
SELECT NOMBRE, APELLIDO
FROM EMPLEADOS;

-- B
SELECT DISTINCT APELLIDO -- / SELECT DISTINCT(APELLIDO) (si hay varios)
FROM EMPLEADOS;

-- C
SELECT *
FROM EMPLEADOS
WHERE APELLIDO = 'López';

-- D
SELECT E.NOMBRE, E.APELLIDO, D.NOMBRE
FROM EMPLEADOS E, DEPARTAMENTO D
WHERE E.CLAVE_DEPT = D.CLAVE_DEPT
AND E.NOMBRE LIKE '%a';

-- E
SELECT *
FROM EMPLEADOS
WHERE APELLIDO IN ('López', 'Pérez');

-- F
SELECT NOMBRE, CLAVE_EMP
FROM EMPLEADOS
WHERE CLAVE_DEPT = 4;

-- G
SELECT NOMBRE, APELLIDO
FROM EMPLEADOS
WHERE UPPER(APELLIDO) LIKE 'H%'; -- Comprueba en mayúsculas

-- H
SELECT *
FROM DEPARTAMENTO
WHERE PRESUPUESTO BETWEEN 50000 AND 70000

-- I
SELECT E.CLAVE_EMP, E.NOMBRE, E.APELLIDO
FROM EMPLEADOS E, DEPARTAMENTO D
WHERE E.CLAVE_DEPT = D.CLAVE_DEPT
AND LOWER(D.NOMBRE) = 'contabilidad';

-- J
SELECT EMPLEADOS.NOMBRE AS "NOMBRE_EMPLEADO", EMPLEADOS.APELLIDO, DEPARTAMENTO.NOMBRE AS "NOMBRE_DEPARTAMENTO"
FROM EMPLEADOS, DEPARTAMENTO
WHERE EMPLEADOS.CLAVE_DEPT = DEPARTAMENTO.CLAVE_DEPT;

-- K
SELECT COUNT(E.CLAVE)
FROM EMPLEADOS, DEPARTAMENTO
WHERE EMPLEADOS.CLAVE_DEPT = DEPARTAMENTO.CLAVE_DEPT
AND UPPER(DEPARTAMENTO.NOMBRE) = 'CONTABILIDAD';

-- L
SELECT COUNT(*)
FROM EMPLEADOS E, DEPARTAMENTO D
WHERE E.CLAVE_DEPT = D.CLAVE_DEPT
AND E.NOMBRE LIKE 'J%'
AND D.NOMBRE = 'Manufactura';