-- A
SELECT MAX(PRECIO)
FROM LIBRO;

-- B
SELECT MIN(PRECIO)
FROM LIBRO;

-- C
SELECT MIN(FECHA_SAL)
FROM EDITA
WHERE DNI = 443042293;

/* Para obtener la fecha más baja, también se puede ordenar en ascendente y quedarse con la primera fila:
SELECT *
FROM EDITA
WHERE DNI = 443042293
ORDER BY FECHA_SAL ASC
AND ROWNUM = 1; -- ROWNUM -> LIMIT (en otros entornos)
*/

-- D
SELECT MAX(FECHA_SAL)
FROM EDITA
WHERE DNI = 29110302;

/* Con ROWNUM:
SELECT *
FROM EDITA
WHERE DNI = 29110302
ORDER BY FECHA_SAL DESC
AND ROWNUM = 1;
*/

-- E
SELECT MAX(NUMPAG)
FROM LIBRO
WHERE UPPER(TEMATICA) = 'NOVELA'

-- F
SELECT MIN(NUMPAG)
FROM LIBRO
WHERE TEMATICA IN ('INFANTIL', 'CIENTÍFICA', 'NOVELA', 'CÓMICO');

-- G
SELECT COUNT(DESCRIPCION)
FROM LIBRO
WHERE TEMATICA = UPPER('CIENTTÍFICO')
AND PRECIO BETWEEN 5 AND 15;