-- A
SELECT DNI
FROM EMPLEADO
WHERE UPPER(CIUDAD) IN ('BARCELONA', 'MADRID', 'SEVILLA', 'MÁLAGA')
AND UPPER(NOMBRE) NOT IN ('ANTONIO', 'LUIS')
AND UPPER(PR_APELLIDO) = 'GARCÍA';

-- B
SELECT DNI
FROM EMPLEADO
WHERE UPPER(CIUDAD) != 'SEVILLA'
AND UPPER(CIUDAD) IN ('BARCELONA', 'MADRID')
AND UPPER(NOMBRE) LIKE 'M%';

-- C
SELECT DNI
FROM EMPLEADO
WHERE UPPER(CIUDAD) = 'SEVILLA'
AND UPPER(CIUDAD) NOT IN ('BARCELONA', MADRID)
AND UPPER(NOMBRE) NOT LIKE 'M%';

-- D
SELECT NOMBRE, PR_APELLIDO
FROM EMPLEADO
WHERE UPPER(CIUDAD) IN ('VALENCIA', 'VIZCAYA')
OR UPPER(CIUDAD) LIKE '%A'
ORDER BY PR_APELLIDO DESC; -- Por defecto ASC

-- E
SELECT DNI
FROM EMPLEADO
WHERE UPPER(CIUDAD) = 'BARCELONA'
AND UPPER(NOMBRE) IN ('ANTONIO', 'LUIS', 'IVÁN', 'PEDRO')
AND UPPER(PR_APELLIDO) IN ('GARCÍA', 'CANTOS');
OR UPPER(SG_APELLIDO) IN ('GARCÍA', 'CANTOS');

-- F
SELECT NOMBRE, PR_APELLIDO, SG_APELLIDO
FROM EMPLEADO
WHERE DNI '%4%'
AND (UPPER)NOMBRE IN ('ROSA', 'LUIS', 'RAMÓN', 'ANTONIO');

-- G
SELECT DNI
FROM EMPLEADO
WHERE (UPPER)NOMBRE = 'ANTONIO'
AND (UPPER)PR_APELLIDO NOT LIKE '%C%'
AND (UPPER)SG_APELLIDO IN ('GARCÍA', 'GÓMEZ', 'SÁNCHEZ')
ORDER BY SG_APELLIDO;

-- H
SELECT DNI
FROM EMPLEADO
WHERE SG_APELLIDO IS NULL;